version: "3.8"
services:
  xero-api:
    image: jaypeng2015/show-me-the-money
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    ports:
      - "3002:3002"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - xero-api
